vim.keymap.set("", "<Up>", function()
    print("Shame!")
end)
vim.keymap.set("", "<Down>", function()
    print("Shame!")
end)
vim.keymap.set("", "<Left>", function()
    print("Shame!")
end)
vim.keymap.set("", "<Right>", function()
    print("Shame!")
end)
