[keyboard]
bindings = [
  # this is for my muscle memory - special modifiers for copy/paste to disambiguate from signals
  { key = "C", mods = "Control|Alt", action = "Copy" },
  { key = "V", mods = "Control|Alt", action = "Paste" },
]
