[keyboard]
bindings = [
  # this is for my muscle memory - special modifiers for copy/paste to disambiguate from signals
  { key = "C", mods = "Command|Alt", action = "Copy" },
  { key = "V", mods = "Command|Alt", action = "Paste" },
  # control R and ctrl shift R are used by aerospace, need to ignore them here
  { key = "R", mods = "Control", action = "ReceiveChar" },
  { key = "R", mods = "Control|Shift", action = "ReceiveChar" },
  # hex codes b/c of my ctrl/cmd swap on osx
  { key = "A", mods = "Command", chars = "\u0001" },
  { key = "B", mods = "Command", chars = "\u0002" },
  { key = "C", mods = "Command", chars = "\u0003" },
  { key = "D", mods = "Command", chars = "\u0004" },
  { key = "E", mods = "Command", chars = "\u0005" },
  { key = "G", mods = "Command", chars = "\u0007" },
  { key = "H", mods = "Command", chars = "\u0008" },
  { key = "J", mods = "Command", chars = "\u000A" },
  { key = "K", mods = "Command", chars = "\u000B" },
  { key = "L", mods = "Command", chars = "\u000C" },
  { key = "O", mods = "Command", chars = "\u000F" },
  { key = "P", mods = "Command", chars = "\u0010" },
  { key = "Q", mods = "Command", chars = "\u0011" },
  { key = "R", mods = "Command", chars = "\u0012" },
  { key = "U", mods = "Command", chars = "\u0015" },
  { key = "V", mods = "Command", chars = "\u0016" },
  { key = "W", mods = "Command", chars = "\u0017" },
  { key = "X", mods = "Command", chars = "\u0018" },
  { key = "Z", mods = "Command", chars = "\u001A" },
]
